register:
  path: /register
  controller: UserBundle:RegistrationController:index
  method: GET

register_post:
  path: /register
  controller: UserBundle:RegistrationController:create
  method: POST

test:
  path: /toto
  controller: UserBundle:RegistrationController:toto
  method: GET
